services:
  mongo:
    image: mongo:latest
    container_name: localsvc_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: localservice_db
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: localsvc_be
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URL: mongodb://admin:adminpassword@mongo:27017/localservice_db?authSource=admin
      FRONTEND_URL: http://localhost:5173
      JWT_SECRET: dev_secret_key_12345
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: localsvcfr
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend

volumes:
  mongo_data:

